services:
  postgres:
    image: postgres:16
    container_name: pruebaticket-postgres
    environment:
      POSTGRES_DB: pruebaticket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pruebaticket_pgdata:/var/lib/postgresql/data

volumes:
  pruebaticket_pgdata:
